### ISSUE TITLE
Change the price from info to price given in domain and change the float to BigNumber.

### ISSUE THREAD

**Issue by rekpero** [mmitrasish/ENSMarket#1]
Buy Subdomain need an instance of big number but we have price in floating point. Change it to big number and try buy method once.

**Comment by Abhimanyu121** [comment]
Can you point out where exactly in code ?
It would save me from going through whole code.

**Comment by Abhimanyu121** [comment]
btw here is the snippet you are looking for i guess `let _eth = superWeb3.utils.toWei(eth.toString());`
Pass your float value as string and you will get bignumber

**Comment by rekpero** [comment]
I thinks its not a problem in the frontend but price is already set in the smart contract. So we need to deploy a new smart contract with new prices and get reference from them.

**Closing** #1
